<script>
	import '../app.css';
	import { ParaglideJS } from '@inlang/paraglide-sveltekit';
	import { i18n } from '$lib/i18n';
</script>

<!-- File autogenerated by the Paraglide-SvelteKit CLI - Feel free to edit -->

<ParaglideJS {i18n}>
	<slot></slot>
</ParaglideJS>
