// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TastingOrganizer.Infrastructure.Data;

#nullable disable

namespace TastingOrganizer.Infrastructure.Migrations
{
    [DbContext(typeof(TastingOrganizerContext))]
    [Migration("20241113093120_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TastingOrganizer.Domain.Entities.Flight", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<int>("Index")
                        .HasColumnType("integer")
                        .HasColumnName("index");

                    b.Property<int>("TastingId")
                        .HasColumnType("integer")
                        .HasColumnName("tasting_id");

                    b.Property<string>("Title")
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("pk_flight");

                    b.HasIndex("TastingId")
                        .HasDatabaseName("ix_flight_tasting_id");

                    b.ToTable("flight", (string)null);
                });

            modelBuilder.Entity("TastingOrganizer.Domain.Entities.Score", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Points")
                        .HasColumnType("numeric")
                        .HasColumnName("points");

                    b.Property<int>("TastingParticipantId")
                        .HasColumnType("integer")
                        .HasColumnName("tasting_participant_id");

                    b.Property<int>("WineId")
                        .HasColumnType("integer")
                        .HasColumnName("wine_id");

                    b.HasKey("Id")
                        .HasName("pk_score");

                    b.HasIndex("TastingParticipantId")
                        .HasDatabaseName("ix_score_tasting_participant_id");

                    b.HasIndex("WineId")
                        .HasDatabaseName("ix_score_wine_id");

                    b.ToTable("score", (string)null);
                });

            modelBuilder.Entity("TastingOrganizer.Domain.Entities.Tasting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AccessCode")
                        .HasColumnType("text")
                        .HasColumnName("access_code");

                    b.Property<string>("AdminCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("admin_code");

                    b.Property<string>("Creator")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("creator");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<DateTime>("From")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("from");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("boolean")
                        .HasColumnName("is_published");

                    b.Property<int>("MaxPeopleCount")
                        .HasColumnType("integer")
                        .HasColumnName("max_people_count");

                    b.Property<string>("Organizers")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("organizers");

                    b.Property<string>("Place")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("place");

                    b.Property<decimal>("PricePerPerson")
                        .HasColumnType("numeric")
                        .HasColumnName("price_per_person");

                    b.Property<string>("PublicCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("public_code");

                    b.Property<int>("RevealType")
                        .HasColumnType("integer")
                        .HasColumnName("reveal_type");

                    b.Property<int>("ScoringType")
                        .HasColumnType("integer")
                        .HasColumnName("scoring_type");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("title");

                    b.Property<DateTime?>("To")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("to");

                    b.HasKey("Id")
                        .HasName("pk_tastings");

                    b.ToTable("tastings", (string)null);
                });

            modelBuilder.Entity("TastingOrganizer.Domain.Entities.TastingParticipant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<bool>("Invited")
                        .HasColumnType("boolean")
                        .HasColumnName("invited");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<bool>("NeedsToPay")
                        .HasColumnType("boolean")
                        .HasColumnName("needs_to_pay");

                    b.Property<DateTime?>("PayDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("pay_date");

                    b.Property<int?>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_tasting_participant");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_tasting_participant_user_id");

                    b.ToTable("tasting_participant", (string)null);
                });

            modelBuilder.Entity("TastingOrganizer.Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_user");

                    b.ToTable("user", (string)null);
                });

            modelBuilder.Entity("TastingOrganizer.Domain.Entities.Wine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("FlightId")
                        .HasColumnType("integer")
                        .HasColumnName("flight_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric")
                        .HasColumnName("price");

                    b.Property<string>("Producer")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("producer");

                    b.Property<decimal>("RetailPrice")
                        .HasColumnType("numeric")
                        .HasColumnName("retail_price");

                    b.HasKey("Id")
                        .HasName("pk_wine");

                    b.HasIndex("FlightId")
                        .HasDatabaseName("ix_wine_flight_id");

                    b.ToTable("wine", (string)null);
                });

            modelBuilder.Entity("TastingOrganizer.Domain.Entities.Flight", b =>
                {
                    b.HasOne("TastingOrganizer.Domain.Entities.Tasting", "Tasting")
                        .WithMany("Flights")
                        .HasForeignKey("TastingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_flight_tastings_tasting_id");

                    b.Navigation("Tasting");
                });

            modelBuilder.Entity("TastingOrganizer.Domain.Entities.Score", b =>
                {
                    b.HasOne("TastingOrganizer.Domain.Entities.TastingParticipant", "TastingParticipant")
                        .WithMany("Scores")
                        .HasForeignKey("TastingParticipantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_score_tasting_participant_tasting_participant_id");

                    b.HasOne("TastingOrganizer.Domain.Entities.Wine", "Wine")
                        .WithMany("Scores")
                        .HasForeignKey("WineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_score_wine_wine_id");

                    b.Navigation("TastingParticipant");

                    b.Navigation("Wine");
                });

            modelBuilder.Entity("TastingOrganizer.Domain.Entities.TastingParticipant", b =>
                {
                    b.HasOne("TastingOrganizer.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .HasConstraintName("fk_tasting_participant_user_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TastingOrganizer.Domain.Entities.Wine", b =>
                {
                    b.HasOne("TastingOrganizer.Domain.Entities.Flight", "Flight")
                        .WithMany("Wines")
                        .HasForeignKey("FlightId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_wine_flight_flight_id");

                    b.Navigation("Flight");
                });

            modelBuilder.Entity("TastingOrganizer.Domain.Entities.Flight", b =>
                {
                    b.Navigation("Wines");
                });

            modelBuilder.Entity("TastingOrganizer.Domain.Entities.Tasting", b =>
                {
                    b.Navigation("Flights");
                });

            modelBuilder.Entity("TastingOrganizer.Domain.Entities.TastingParticipant", b =>
                {
                    b.Navigation("Scores");
                });

            modelBuilder.Entity("TastingOrganizer.Domain.Entities.Wine", b =>
                {
                    b.Navigation("Scores");
                });
#pragma warning restore 612, 618
        }
    }
}
