/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/Tasting": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["CreateTastingDto"];
                    "text/json": components["schemas"]["CreateTastingDto"];
                    "application/*+json": components["schemas"]["CreateTastingDto"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/Tasting/{code}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    code: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["SaveTastingModel"];
                    "text/json": components["schemas"]["SaveTastingModel"];
                    "application/*+json": components["schemas"]["SaveTastingModel"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        CreateTastingDto: {
            title?: string | null;
        };
        /**
         * Format: int32
         * @enum {integer}
         */
        RevealType: 0 | 1 | 2;
        SaveTastingModel: {
            /** Format: int32 */
            id?: number;
            /** Format: date-time */
            from?: string;
            /** Format: date-time */
            to?: string | null;
            description?: string | null;
            /** Format: int32 */
            maxPeopleCount?: number;
            title?: string | null;
            /** Format: double */
            pricePerPerson?: number;
            place?: string | null;
            creator?: string | null;
            organizers?: string | null;
            scoringType?: components["schemas"]["ScoringType"];
            revealType?: components["schemas"]["RevealType"];
            adminCode?: string | null;
            accessCode?: string | null;
            isPublished?: boolean;
        };
        /**
         * Format: int32
         * @enum {integer}
         */
        ScoringType: 0 | 1 | 2 | 3;
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
