name: Deploy to GitHub pages

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build Vue
        run: |
              npm ci
              npm run build
      - name: Deploy Vue
        run: |
              cd dist
              git init
              git add -A
              git config --global user.email "arikael@mailbox.org"
              git config --global user.name "Arikael"
              git commit -m 'deploy'
              git push -f https://arikael:${{ secrets.GITHUB_TOKEN }}@github.com/arikael/tasting-organizer.git master:gh-pages

